name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-release:
    runs-on: self-hosted
    needs: tagpr
    if: needs.tagpr.outputs.tag != ''
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.tagpr.outputs.tag }}
          fetch-depth: "0"
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.5"
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
